return {
    { "tpope/vim-surround" },
    { "tpope/vim-fugitive" },
    { "tpope/vim-rhubarb" },
    { "f-person/git-blame.nvim" },
    { "airblade/vim-gitgutter" },
    { "simnalamburt/vim-mundo" },
    { "mitchellh/tree-sitter-proto" },
    { "tree-sitter/tree-sitter-go" },
    { "windwp/nvim-spectre" },
    { "danilamihailov/beacon.nvim" },
    require('plugins.installs.hlslens'),
    require('plugins.installs.noice'),
    require('plugins.installs.rust-tools'),
    require('plugins.installs.no-neck-pain'),
    require('plugins.installs.eslint'),
    require('plugins.installs.twilight'),
    require('plugins.installs.lsp-colors'),
    require('plugins.installs.trouble'),
    require('plugins.installs.colortils'),
    require('plugins.installs.todo-comments'),
    require('plugins.installs.hop-install'),
    require('plugins.installs.silicon'),
    require('plugins.installs.winpick'),
    require('plugins.installs.goto-preview'),
    require('plugins.installs.persistance'),
    require('plugins.installs.peek'),
    require('plugins.installs.scrollbar'),
    require('plugins.installs.mini-indentscope'),
}
