#!/bin/bash

cp ~/.config/gtk-3.0/dark.ini ~/.config/gtk-3.0/settings.ini
cp ~/.config/xfce4/terminal/themes/tokyo/terminalrc ~/.config/xfce4/terminal/terminalrc 
feh --bg-fill /home/edjubert/backgrounds/astronaut_EOS_dark.jpeg
# feh --bg-fill /home/edjubert/backgrounds/Lune/0005_DSC05498-Modifier.jpg
