#!/bin/bash

SLOP=`slop`
DIMENSIONS=`echo $SLOP | cut -d '+' -f 1`
X=`echo $SLOP | cut -d '+' -f 2`
Y=`echo $SLOP | cut -d '+' -f 3`
FIXED_DIMENSIONS="pad=ceil($X/2)*2:ceil($Y/2)*2"
FRAMERATE=30
DATE=`date +%s`

echo $FIXED_DIMENSIONS

ffmpeg \
  -video_size $DIMENSIONS \
  -vf "crop=trunc(iw/2)*2:trunc(ih/2)*2" \
  -framerate $FRAMERATE \
  -f x11grab \
  -i :0.0+$X,$Y \
  -c:v libx264 \
  -crf 18 \
  -preset ultrafast \
  -c:a aac \
  -strict -2 \
  -b:a 128k \
  -pix_fmt \
  yuv420p \
  -f mp4 \
  -y /tmp/screenshot-$DATE.mp4
