#!/bin/bash

if [ "$*" = "quit" ]
then
  exit 0
fi

if [ "$@" ]
then
  desc="$*"
  already=$(echo "$desc" | grep "*" | wc -l)
  if [ "$already" != "0" ]
  then
    exit 0
  fi

  if [ "$desc" = "US" ]
  then
    setxkbmap us
    notify-send "Keyboard layout is now Qwerty"
  elif [ "$desc" = "Colemak" ]
  then
    setxkbmap us -variant colemak
    notify-send "Keyboard layout is now Colemak"
  fi
else
  layout=$(setxkbmap -query | grep layout | awk '{split($0,a," ");print a[2]}')
  variant=$(setxkbmap -query | grep variant | awk '{split($0,a," ");print a[2]}')

  if [ "$layout" = "us" ]
  then
    if [ "$variant" = "colemak" ]
    then
      echo "US"
      echo "* Colemak"
    else
      echo "* US"
      echo "Colemak"
    fi
  else
      echo "US"
      echo "Colemak"
  fi
  echo "quit"
fi
