#!/bin/bash

if [ "$*" = "quit" ]
then
  exit 0
fi

if [ "$@" ]
then
  desc="$*"
  device=$(pamixer --list-sources | awk '{split($0,a," "); print a[2]}' | awk '{gsub(/"/, "", $0); print $0}')
  isAlready=$(echo "$desc" | grep "\->")
  if [ "$isAlready" != "" ]
  then
    exit 0
  elif pactl set-default-source "$desc"
  then
    notify-send "Activated: $desc"
  else
    notify-send "Error activating $desc"
  fi
else
  echo -en "\x00prompt\x1fSelect Input\n"
  running=$(wpctl status | grep "Audio/Source" | awk '{split($0,a," "); print a[3]}')
  for x in $(pamixer --list-sources | awk '{split($0,a," "); print a[2]}' | awk '{gsub(/"/, "", $0); print $0}')
  do
    isMonitor=$(echo "$x" | grep "monitor")
    if [ "$x" = "$running" ]
    then
      echo "-> $x"
    elif [ "$isMonitor" = "" ]
    then
      echo "$x"|xargs
    fi
  done
  echo "quit"
fi
