#!/bin/bash

if [ "$1" == "inc" ]; then
    /usr/bin/brightnessctl set 10%+
fi

if [ "$1" == "dec" ]; then
    /usr/bin/brightnessctl set 10%-
fi

BRIGHTNESS=$(/usr/bin/brightnessctl get)
MAX=$(/usr/bin/brightnessctl max)
PERCENT=$(echo $((BRIGHTNESS*100/MAX)))

NOTI_ID=$(notify-send.py "Backlight" "$PERCENT%" \
                         --hint string:image-path:video-display boolean:transient:true \
                                int:has-percentage:$PERCENT \
                         --replaces-process "brightness-popup")
